# send
[plugin]
    enabled=true

[servers]
    server-blacklist=false
    servers-blacklisted = ["server-1", "server-2"]


[messages]
    # /send
    send-success-plural="<yellow>Sent <players> players to <server>.</yellow>"
    send-success-singular="<yellow>Sent <player> to <server>.</yellow>"


[developer-info]
    config-version=0.2